kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: can-build
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create